name: 'RBAC in Github Action'
description: 'Check if the user triggering the workflow is allowed to proceed.'
inputs:
  permissions-file:
    description: 'Path to the permissions.yml file'
    required: true
  actor:
    description: 'GitHub actor triggering the workflow'
    required: true
    default: ${{ github.actor }}

runs:
  using: 'composite'
  steps:
  - name: Check Permissions
    run: |
      if ! grep -qx "${{ inputs.actor }}" "${{ inputs.permissions-file }}"; then
        echo "-----------------ERROR--------------------"
        echo "User ${{ inputs.actor }} is not allowed to trigger this workflow."
        echo "------------------------------------------"
        exit 1
      fi
    shell: bash
